### ISSUE TITLE
Error: java.util.concurrent.TimeoutException: Timed out waiting for the service connection

### ISSUE THREAD

**Issue by alonp99** [sparkfabrik/sparkfabrik-react-native-idfa-aaid#18]
Hey,

I'm getting this error: `Error: java.util.concurrent.TimeoutException: Timed out waiting for the service connection` after calling`ReactNativeIdfaAaid.getAdvertisingInfo()` on some devices.

This is the stack trace:
```
Error: java.util.concurrent.TimeoutException: Timed out waiting for the service connection
  at getAdvertisingInfo(node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:55)
  at destroy(hooks/useAdvertisingInfo.ts:11:25)
  at commitHookEffectList(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:4843:55)
  at flushPassiveEffectsImpl(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6758:15)
  at flushPassiveEffects(node_modules/scheduler/cjs/scheduler.production.min.js:18:438)
  at d(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6725:9)
  at Y(node_modules/scheduler/cjs/scheduler.production.min.js:17:184)
  at t(node_modules/scheduler/cjs/scheduler.production.min.js:11:145)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:135:7)
  at apply(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:387:7)
  at __callFunction(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:425:42)
  at fn(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:12)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:373:9)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:10)
  at value([native code])
```

Didn't find a solid solution online, will appreciate any help :)

**Comment by edodusi** [comment]
Hi @alonp99, can you please provide a bit more context about this issue?
Android version, RN version, the code snippet you applied for calling the API.

Thanks.

**Comment by dtanh57** [comment]
Same issue.
My project information: Android 12, RN 0.67.
I use AppState to get aaid when app state is active.
Sometimes i get aaid, sometimes not.

**Comment by likesebiii** [comment]
There is a race condition somewhere. "Error: java.util.concurrent.TimeoutException: Timed out waiting for the service connection" was thrown when the main thread was overwhelmed and I was trying to get the aaid. 

Adding a timeout solved the problem for me.
